# config.toml
[server]
# Declare port where up server
port = ":PORT"
# Declare IP address to allow access
origin = "ORIGIN"
# Declare database connection url (default db: postgres)
database_url = "DRIVER://USER:PASSWORD@HOST:PORT/DB_NAME?sslmode=disable"
# Declare JWT secret to encrypt access token's (recommended: SHA256)
jwt_secret = "SECRET"
