version: '3.8'
services:
  database:
    image: postgres:14-alpine
    container_name: db_minerva
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: minerva
    ports:
      - "5432:5432"
    volumes:
      - ./config/database/postgres/seed:/mnt/seed
    networks:
      - database-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_minerva
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5000:80"
    depends_on:
      - database
    networks:
      - database-network

networks: 
  database-network:
    driver: bridge